---
title: "Anexo A - Trabalho Prático 1 de Estatística Computacional"
subtitle: "Código fonte dos arquivos selecao.R, insercao.R, quicksort.R e vetores.R"
output: pdf_document
---

Este Anexo A contém os _scripts_ implementados pelo grupo para os algoritmos e a "escolha" dos vetores aleatórios com seus respectivos _seeds_.

## selecao.R

A implementação do algoritmo de seleção inspira-se no algoritmo mostrado em sala de aula:


```{#selecao.R .numberLines}
#' Title selecao
#'
#' @param vetor de dados unidimensional
#'
#' @return Para n > 1: Lista com o data frame tab.resumo com o C(n) e M(n) para o vetor selecionado
#'         e o head (10 primeiras posições) do vetor ordenado
#'         Para n = 1: o próprio vetor
#' @export 
#'
#' @examples >selecao(c("x","j","j","n","m","k","a")) 
#'            [[1]]
#'                                          resultado
#'            Número de Comparações: C(n)          13
#'            Número de movimentações: M(n)        39
#'
#'            [[2]]
#'            [1] "a" "j" "j" "k" "m" "n"
#'            
#'           >selecao("x")
#'           [1] "x"
selecao <- function(vetor){
  tamanho = length(vetor)
  comparacoes = 0 
  movimentacoes = 0 
if(length(vetor) > 1){
  for(i in 1:(tamanho - 1)){
    for(j in i:tamanho){
      if(vetor[i] > vetor[j]){
        minimo <- vetor[j]
        vetor[j] = vetor[i]
        vetor[i] = minimo
        comparacoes <- comparacoes + 1
        movimentacoes <- movimentacoes + 3
      }
    }
  }
  
}
  else{
    return(vetor)
  }
  tab.resumo <- data.frame(resultado = c(comparacoes,movimentacoes),
                           row.names = c("Número de Comparações: C(n)", "Número de movimentações: M(n)"))
  return(list(tab.resumo, head(vetor)))}

```
## insercao.R
A implementação do algoritmo de inserção inspira-se no algoritmo mostrado em sala de aula:

```{#insercao.R .numberLines}
#' Title insercao
#'
#' @param vetor: vetor de dados unidimensional
#'
#' @return Para n > 1: Lista com data frame tab.resumo com o C(n) e M(n) para o vetor selecionado
#'                     e o head (10 primeiras posições) do vetor ordenado
#'         Para n = 1: o próprio vetor
#' @export
#'
#' @examples > insercao(c("x","j","j","n","m","k","a"))
#'            [[1]]
#'                                          resultado
#'            Número de Comparações: C(n)          14
#'            Número de movimentações: M(n)        28
#'
#'            [[2]]
#'            [1] "a" "j" "j" "k" "m" "n"
#'           > insercao("x")
#'            [1] "x"
insercao <- function(vetor){
  tamanho = length(vetor)
  comparacoes = 0 
  movimentacoes = 0 
  
  if(length(vetor) > 1){
    for(j in 2:length(vetor)){
      pivo <- vetor[j]
      i <- j-1
      while(i>0 && vetor[i] > pivo){
        vetor[i+1] <- vetor[i]
        i<-i-1
        comparacoes <- comparacoes + 1
        movimentacoes <- movimentacoes + 2
      }
        vetor[i+1] <- pivo
        
    }
    tab.resumo <- data.frame(resultado = c(comparacoes,movimentacoes),
                             row.names = c("Número de Comparações: C(n)", 
                                           "Número de movimentações: M(n)"))
    return(list(tab.resumo, head(vetor)))
    }
  

  else{
    return(vetor)
  }
  
}
```

## quicksort.R

Um breve comentário sobre a implementação de `quicksort()`. Usualmente, utiliza-se uma função auxiliar para fazer a partição do objeto a ser ordenado, notadamente seguindo a filosofia do "dividir para conquistar" que permeia o algoritmo. No entanto, como foi pedido no Trabalho Prático para que os alunos contassem o número de comparações e movimentações, isso introduziu um fator de complexidade com o qual o R não trabalha bem: múltiplos retornos para funções. O que se pensou inicialmente seria em implementar a função auxiliar com cinco parâmetros, notadamente: vetor, esquerda (índice a partir do qual será feita a ordenação, _default_ = 1, direita (índice até onde será feita a ordenação, _default_ = comprimento do vetor), comparacoes e movimentacoes). Finalmente, decidimos por implementar o algoritmo tomando comparações e movimentações como variåveis globais e, a partir das regras de escopo da linguagem, incrementar seu valor a partir do operador `<<-`. A função `quicksort()` chama uma função _helper_ `quicksort.helper()`, que é onde de fato acontece a ordenação. Isso obviamente reduz consideravelmente a eficiência do algoritmo, mas, como mostrado ao longo do relatório do trabalho e verificado pelas ordens dos algoritmos, essa perda de eficiência devido à implementação é relativamente compensada conforme o tamanho do vetor cresce.

```{#quicksort.R .numberLines}
comparacoes <- 0
movimentacoes <- 0

#' Title quicksort
#'
#' @param vetor vetor a ser ordenado
#' @param esquerda primeiro índice a partir do qual desejamos ordenar (default = 1)
#' @param direita último índice até onde deseja-se ordenar (default = comprimento do vetor)
#'
#' @return Para n > 1: Lista com data frame tab.resumo com o C(n) e M(n) para o vetor selecionado
#'                     e o head (10 primeiras posições) do vetor ordenado
#'         Para n = 1: o próprio vetor
#' @export
#'
#' @examples> quicksort(c(2,3,1))
#'            [[1]]
#'            resultado
#'            Número de Comparações: C(n)           1
#'            Número de movimentações: M(n)         6
#'            [[2]]
#'            [1] 1 2 3
quicksort <- function(vetor, esquerda = 1, direita = length(vetor)){
  if(length(vetor) > 1){

  vetor <- quicksort.helper(vetor, esquerda, direita)
  tab.resumo <- data.frame(resultado = c(comparacoes,movimentacoes),
                           row.names = c("Número de Comparações: C(n)", 
                                         "Número de movimentações: M(n)"))
  return(list(tab.resumo, head(vetor)))
  }
  else{
    return(vetor)
    }
}

#' Title quicksort.helper helper da função quicksort acima. Notar que esta função é recursiva
#'
#' @param vetor vetor a ser ordenado
#' @param esquerda primeiro índice a partir do qual desejamos ordenar (default = 1)
#' @param direita último índice até onde deseja-se ordenar (default = comprimento do vetor)
#'
#' @return vetor ordenado
#' @export quicksort()
#'
#' @examples
quicksort.helper <- function(vetor,esquerda=1,direita=length(vetor)){
  pivo = vetor[floor(esquerda+direita)/2]
  i=esquerda
  j=direita
  while(i <= j){
    while(vetor[i]<pivo){
      i = i + 1
      comparacoes <<- comparacoes + 1
    }
    while(vetor[j]>pivo){
      j = j - 1
      comparacoes <<- comparacoes + 1
    }
    if( i <= j){
      buffer <- vetor[i]
      vetor[i] <- vetor[j]
      vetor[j] <- buffer
      i = i+1
      j = j-1
      movimentacoes <<- movimentacoes + 3
    }
  }
if(esquerda < j){
  vetor <- qs2(vetor,esquerda, j)
}
if(i < direita){
  vetor <- qs2(vetor,i,direita)
}
  
  return(vetor)
}
```

## vetores.R

Este _script_ indica os _seeds_ utilizados e qual o comando para obtenção dos vetores inicialmente não-ordenados. 

```{#vetores.R .numberLines}
# Vetor aleatório de tamanho 10;
set.seed(1986)
vetor10 <- sample.int(10)

# Vetor aleatório de tamanho 100;
set.seed(1979)
vetor100 <- sample.int(100)

# Vetor aleatório de tamanho 1000;
set.seed(42)
vetor1000 <- sample.int(1000)

# Vetor aleatório de tamanho 10000;
set.seed(51)
vetor10000 <- sample.int(10000)

# Vetor aleatório de tamanho 10000;
set.seed(2016)
vetor50000 <- sample.int(50000)
```